# Generated by Django 4.0.1 on 2022-11-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='ID',
            field=models.CharField(default=1, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
