# Generated by Django 4.0.1 on 2022-11-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_post_id_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ID',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
