# Generated by Django 4.0.1 on 2022-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_comment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
